[workspace]
authors = ["Dan Rosenbaum <danro@cs.haifa.ac.il>"]
channels = ["conda-forge"]
name = "flowNP"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
pyyaml = ">=6.0.2,<7"
matplotlib = ">=3.10.5,<4"
tqdm = ">=4.67.1,<5"
pytorch-gpu = ">=2.7.1,<3"
addict = ">=2.4.0,<3"
xarray = ">=2025.8.0,<2026"
prettytable = ">=3.16.0,<4"
torchvision = ">=0.23.0,<0.24"
timm = ">=1.0.20,<2"
diffusers = ">=0.35.1,<0.36"

[pypi-dependencies]
attrdictionary = ">=1.0.0, <2"
flow-matching = ">=1.0.10, <2"

[system-requirements]
cuda = "12.6"
